name: Clear Menus

on:
    workflow_dispatch:

jobs:
    clear-menus:
        runs-on: ubuntu-latest

        steps:
            - name: Send clear request
              run: |
                curl -X POST "${{ secrets.SYNC_API_URL }}/mensa/clear" \
                -H "X-Internal-Key: ${{ secrets.SYNC_API_KEY }}" \
                -H "Content-Type: application/json"