name: Menu Scraper

on:
  workflow_dispatch:

jobs:
  scrape-and-sync:
      runs-on: ubuntu-latest

      defaults:
        run:
          working-directory: menu-scraper

      steps:
          - name: Checkout repository
            uses: actions/checkout@v6
          
          - name: Check if menus already scraped
            id: check_menus
            run: |
              RESPONSE=$(curl -sf "${{ secrets.SYNC_API_URL }}/mensa/scraped-status" -H "X-Internal-Key: ${{ secrets.SYNC_API_KEY }}")
              SCRAPED=$(echo "$RESPONSE" | jq -r '.data.scraped')
              echo "scraped=$SCRAPED" >> "$GITHUB_OUTPUT"

          - name: Set up Go
            if: steps.check_menus.outputs.scraped != 'true'
            uses: actions/setup-go@v6
            with:
              go-version: 'stable'
              cache-dependency-path: menu-scraper/go.sum
          
          - name: Install dependencies
            run: |
              go mod download
          
          - name: Build scraper
            run: |
              go build -o scraper ./cmd/main.go

          - name: Run scraper
            env:
              # Internal
              PORT: 3001
              SYNC_API_KEY: ${{ secrets.SYNC_API_KEY  }}
              SYNC_API_URL: ${{ secrets.SYNC_API_URL }}
              RATE_LIMIT: 5

              # Gemini
              GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
              GEMINI_MODEL: gemini-3.1-flash-lite
              GEMINI_PROMPT_FILE_NAME: analysis_v5.txt

              # Scraper
              MAX_CONCURRENCY: 3
              REQUEST_DELAY_MS: 1500

              # Other
              STORY_API_URL: ${{ secrets.STORY_API_URL }}
              GO_ENV: production
            run: |
              ./scraper