name: Test Dispatch
on:
    push:
        branches:
            - feat/adding-cron-jobs
    workflow_dispatch:
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - run: echo "dispatched on ${{ github.ref }}"